### ISSUE TITLE
Love couple mod is out of date

### ISSUE THREAD

**Issue by tartsharpcobra** [Woodi-dev/Among-Us-Love-Couple-Mod#10]
Since the new among us update, the love couple mod is not working. it is out of date.

**Comment by Woodi-dev** [comment]
Yes. I will update it in the next days.

**Comment by tartsharpcobra** [comment]
Thank you!

**Comment by tartsharpcobra** [comment]
btw, can you make a new mod woodi-dev?

**Comment by Milan2011** [comment]
No

Von meinem iPhone gesendet
