### ISSUE TITLE
Compatibility with mods ?

### ISSUE THREAD

**Issue by Snowad14** [Woodi-dev/Among-Us-Love-Couple-Mod#2]
I know that it is surely not for you to do it, and I do not know if it is possible, but this mod does not allow any compatibility with the others, every time I have a black screen even with your old one sheriff mod (ps: your lover mod is really cool, but without being able to add another mod it quickly becomes boring)

**Comment by Hardel-DW** [comment]
Personally, I modified the source code to remove the black screen;

I removed the IntroCutScene and modify RPC

**Comment by Kriasrub** [comment]
> Personally, I modified the source code to remove the black screen;
> 
> I removed the IntroCutScene and modify RPC


Could you explain that to a person who has no clue how to do that?
