### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by Light-Oxygen** [Woodi-dev/Among-Us-Love-Couple-Mod#8]
Hello,
I can't launch the game, after the IntrocCutScenePath I get a black screen during the whole game. 

Step to repro:
Launch the game with your mod and the last publication of your mod.

**Comment by Woodi-dev** [comment]
can you paste the logoutput.txt file ?

**Comment by Light-Oxygen** [comment]
After checking, the problem is not relevant to the mod, thanks.
